var NAWAL_DATA={
  "_meta": {
    "tradition": "K'iche' (Cholq'ij), correlation GMT 584283",
    "source": "Interpretaciones resumidas y parafraseadas a partir de C. Barrios, El Libro del Destino (Cholsamaj). Para validar por el Ajq'ij antes de publicar.",
    "status": "DRAFT — needs validation",
    "language": "es"
  },
  "nawales": [
    {"index":0,"kiche":"Imox","yucateco":"Imix","mexica":"Cipactli","direccion":"Norte","elemento":"Aire","clave":"Lado izquierdo, lo inusual.","desarrollo":"Acrecentar los poderes internos.",
     "energiaDelDia":"Día favorable para fortalecer el espíritu y las capacidades internas; se pide por la lluvia y por la pureza de ríos, lagos y mares."},
    {"index":1,"kiche":"Iq'","yucateco":"Ik'","mexica":"Ehecatl","direccion":"Sur","elemento":"Agua","clave":"El viento, lo cristalino.","desarrollo":"La pureza, la claridad.",
     "energiaDelDia":"Día de renovación y de vientos que limpian la mente. Propicio para sanar estados emocionales pesados, soltar rencores y fortalecer la oración y el poder mental."},
    {"index":2,"kiche":"Aq'ab'al","yucateco":"Akb'al","mexica":"Calli","direccion":"Este","elemento":"Fuego","clave":"Amanecer y dualidad.","desarrollo":"Oportunidad en el cambio.",
     "energiaDelDia":"Día para pedir claridad en el camino y nuevas oportunidades; saca a la luz lo oculto. Favorable para la estabilidad, un buen trabajo o negocio."},
    {"index":3,"kiche":"K'at","yucateco":"K'an","mexica":"Cuetzpallin","direccion":"Oeste","elemento":"Tierra","clave":"La red, el enredo.","desarrollo":"Claridad interna, no intromisión.",
     "energiaDelDia":"Día para desatar nudos: enredos, vicios, influencias negativas y conflictos emocionales o de pareja. También se pide abundancia y fertilidad, evitando el fanatismo."},
    {"index":4,"kiche":"Kan","yucateco":"Chikchan","mexica":"Coatl","direccion":"Norte","elemento":"Aire","clave":"La energía, fuego interno.","desarrollo":"Develar información interior; manejo de la energía-poder.",
     "energiaDelDia":"Día de fuerza física y de fuego interior, de evolución espiritual. Favorece el retorno de lo perdido, la reconciliación y el equilibrio en la pareja."},
    {"index":5,"kiche":"Kame","yucateco":"Kimi","mexica":"Miquiztli","direccion":"Sur","elemento":"Agua","clave":"Claridad, renacer.","desarrollo":"Resurgir a la espiritualidad.",
     "energiaDelDia":"Día de contacto con los ancestros y de acceso al conocimiento superior. Se pide protección en viajes y alejar enfermedades graves y accidentes."},
    {"index":6,"kiche":"Kej","yucateco":"Manik'","mexica":"Mazatl","direccion":"Este","elemento":"Fuego","clave":"Armonía, naturaleza.","desarrollo":"Trabajo con los cuatro elementos.",
     "energiaDelDia":"Día de armonía con la naturaleza y de equilibrio con los cuatro elementos. Conviene cuidarse de la traición."},
    {"index":7,"kiche":"Q'anil","yucateco":"Lamat","mexica":"Tochtli","direccion":"Oeste","elemento":"Tierra","clave":"Semilla, plantar.","desarrollo":"Germinar, concretizar.",
     "energiaDelDia":"Día de siembra: iniciar relaciones de amor o de negocios, reconquistar o retomar lo que se daba por perdido."},
    {"index":8,"kiche":"Toj","yucateco":"Muluk","mexica":"Atl","direccion":"Norte","elemento":"Aire","clave":"El fuego y los pagos.","desarrollo":"Liberación del pasado.",
     "energiaDelDia":"Día del fuego sagrado y de la ley de causa y efecto: propicio para ofrendar, saldar deudas y nivelar con la justicia. (Barrios no incluye sección 'Energía del Día' para Toj; síntesis del significado.)"},
    {"index":9,"kiche":"Tz'i'","yucateco":"Ok","mexica":"Itzcuintli","direccion":"Sur","elemento":"Agua","clave":"La ley, autoridad.","desarrollo":"Eliminar el autoritarismo; cultivar amor.",
     "energiaDelDia":"Día de la ley y la autoridad: se pide por asuntos legales y por la intervención divina para resolver cualquier tipo de problema."},
    {"index":10,"kiche":"B'atz'","yucateco":"Chwen","mexica":"Ozomatli","direccion":"Este","elemento":"Fuego","clave":"Buscar respuesta en el tiempo y el espacio.","desarrollo":"Creatividad, servicio comunitario.",
     "energiaDelDia":"El mejor día para uniones y para ordenar o iniciar cualquier planificación. Protege a los artistas, favorece las cosechas y la resolución de asuntos familiares."},
    {"index":11,"kiche":"E","yucateco":"Eb'","mexica":"Malinalli","direccion":"Oeste","elemento":"Tierra","clave":"El camino sagrado.","desarrollo":"La experiencia se adquiere en los viajes y con los ancianos.",
     "energiaDelDia":"El mejor día para negocios, negociaciones y firma de contratos. Auspicia los viajes y la comunicación, especialmente con quienes están lejos."},
    {"index":12,"kiche":"Aj","yucateco":"B'en","mexica":"Acatl","direccion":"Norte","elemento":"Aire","clave":"Abundancia y el renacer.","desarrollo":"Retorno al origen, proyección social.",
     "energiaDelDia":"Día de protección del hogar, de los animales y las plantas. Trae resurgimiento, retorno a casa, buen tiempo y cosechas; ayuda a armonizarse con los demás."},
    {"index":13,"kiche":"I'x","yucateco":"Ix","mexica":"Ocelotl","direccion":"Sur","elemento":"Agua","clave":"Paciencia, astucia, la acción.","desarrollo":"Aprendizaje interno, alta magia.",
     "energiaDelDia":"Día de fuerza interior para transformar lo negativo: retirarse, meditar, replantear la vida y diseñar una nueva estrategia. Día de magia y de energías sutiles."},
    {"index":14,"kiche":"Tz'ikin","yucateco":"Men","mexica":"Cuauhtli","direccion":"Este","elemento":"Fuego","clave":"Intermediación entre el cielo y la tierra.","desarrollo":"Intuición, sueños y adivinación.",
     "energiaDelDia":"El mejor día para el amor y para pedir abundancia personal y comunitaria; protege los negocios. En lo espiritual dominan la intuición, la visión y los sueños reveladores."},
    {"index":15,"kiche":"Ajmaq","yucateco":"Kib'","mexica":"Cozcacuauhtli","direccion":"Oeste","elemento":"Tierra","clave":"Búsqueda de expresión y transmisión.","desarrollo":"Perdón y servicio personal.",
     "energiaDelDia":"El día más propicio para dar y pedir perdón y evitar confrontaciones. Favorece la curación, la defensa de los desposeídos y la armonía con la Madre Tierra."},
    {"index":16,"kiche":"No'j","yucateco":"Kab'an","mexica":"Ollin","direccion":"Norte","elemento":"Aire","clave":"Conocimiento y sabiduría.","desarrollo":"Transmisión de la mente, claridad.",
     "energiaDelDia":"Día para alimentar la mente y la memoria, pedir claridad y señales, armonizar relaciones, y convertir conocimiento y experiencia en sabiduría."},
    {"index":17,"kiche":"Tijax","yucateco":"Etz'nab'","mexica":"Tecpatl","direccion":"Sur","elemento":"Agua","clave":"Cuchillo de doble filo.","desarrollo":"Guerrero; cortar energías negativas.",
     "energiaDelDia":"Día para pedir salud y sanar lo difícil; para cortar enemistades, energías negativas, relaciones o sociedades que ya no sirven. También se pide inteligencia y memoria."},
    {"index":18,"kiche":"Kawoq","yucateco":"Kawak","mexica":"Quiahuitl","direccion":"Este","elemento":"Fuego","clave":"Abundancia, la comunidad.","desarrollo":"Trabajo comunitario, desapego.",
     "energiaDelDia":"El mejor día para pedir por el bien común y la familia: resolver conflictos familiares, problemas económicos o de convivencia. Atrae abundancia a los negocios y buen clima a los cultivos."},
    {"index":19,"kiche":"Ajpu","yucateco":"Ajaw","mexica":"Xochitl","direccion":"Oeste","elemento":"Tierra","clave":"Cazador, certeza y seguridad.","desarrollo":"Vencer las pruebas espirituales.",
     "energiaDelDia":"Día de certeza y seguridad para planificar y alcanzar metas; día de renovación, de fertilidad y de seguridad emocional. Da fuerza y valor para vencer obstáculos."}
  ]
}
;
